<<<<<<< HEAD
# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-27 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('draw_volts', models.IntegerField()),
                ('draw_amps', models.IntegerField()),
                ('draw_watts', models.IntegerField()),
                ('alternating_current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DesignProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LoadAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_usage', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Designer.Accessory')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Designer.Load')),
            ],
        ),
        migrations.CreateModel(
            name='PowerProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_camping', models.BooleanField()),
                ('vehicular_moves', models.IntegerField()),
                ('days_autonomous', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('warranty', models.TextField(blank=True)),
                ('mfgPartNumber', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserDesignProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Designer.DesignProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=30)),
                ('panel_type_preference', models.CharField(max_length=1)),
                ('design_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_install', to='System_Designer.DesignProfile')),
            ],
        ),
        migrations.CreateModel(
            name='batteryProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System_Designer.Product')),
                ('ahCapacity', models.PositiveIntegerField()),
                ('operatingVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('chargingCurrentMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('chargingCurrentFloat', models.DecimalField(decimal_places=1, max_digits=4)),
                ('chargingCurrentEqualize', models.DecimalField(decimal_places=1, max_digits=4)),
                ('chargingTempCompensation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('terminalType', models.CharField(max_length=200)),
            ],
            bases=('System_Designer.product',),
        ),
        migrations.CreateModel(
            name='chargeControllerProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System_Designer.Product')),
                ('conversionType', models.CharField(max_length=200)),
                ('maxBattCurrent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('loadCurrentRating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('openCircuitVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('peakEffieciency', models.DecimalField(decimal_places=1, max_digits=4)),
                ('batteryVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('batteryVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('voltageAccuracy', models.DecimalField(decimal_places=1, max_digits=4)),
                ('selfConsumption', models.DecimalField(decimal_places=1, max_digits=4)),
                ('surgeProtection', models.BooleanField(default=True)),
                ('operatingTempMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wireSizeIn', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wireSizeOut', models.DecimalField(decimal_places=1, max_digits=4)),
                ('batteryTemperatureSensor', models.BooleanField(default=True)),
                ('chargeModes', models.CharField(max_length=200)),
            ],
            bases=('System_Designer.product',),
        ),
        migrations.CreateModel(
            name='chargerProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System_Designer.Product')),
                ('dcOuputVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputAmperageContinuous', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dcOutputVoltageFullLoad', models.DecimalField(decimal_places=1, max_digits=4)),
                ('maxPowerOutput', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageFrequency', models.IntegerField()),
                ('maxAcCurrent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('effeciency', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMin', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            bases=('System_Designer.product',),
        ),
        migrations.CreateModel(
            name='inverterChargerProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System_Designer.Product')),
                ('outputWattsContinuous', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputWattsSurge', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputCurrentContinuous', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputFreqency', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputWaveform', models.CharField(max_length=200)),
                ('effeciencyFullLoad', models.DecimalField(decimal_places=1, max_digits=4)),
                ('effeciencyPeak', models.DecimalField(decimal_places=1, max_digits=4)),
                ('noLoadDraw', models.DecimalField(decimal_places=1, max_digits=4)),
                ('offModeDraw', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acInputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acInputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acTransferRelayAmps', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('batteryVoltageNominal', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lowBatteryCutoutLow', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lowBatteryCutoutMid', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lowBatteryCutoutHigh', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acRecepticles', models.BooleanField(default=True)),
                ('operatingTempMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dcOuputVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputAmperageContinuous', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dcOutputVoltageFullLoad', models.DecimalField(decimal_places=1, max_digits=4)),
                ('maxPowerOutput', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageFrequency', models.IntegerField()),
                ('maxAcCurrent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('effeciency', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            bases=('System_Designer.product',),
        ),
        migrations.CreateModel(
            name='inverterProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System_Designer.Product')),
                ('outputWattsContinuous', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputWattsSurge', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputCurrentContinuous', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputFreqency', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputWaveform', models.CharField(max_length=200)),
                ('effeciencyFullLoad', models.DecimalField(decimal_places=1, max_digits=4)),
                ('effeciencyPeak', models.DecimalField(decimal_places=1, max_digits=4)),
                ('noLoadDraw', models.DecimalField(decimal_places=1, max_digits=4)),
                ('offModeDraw', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acInputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acInputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acTransferRelayAmps', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('batteryVoltageNominal', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lowBatteryCutoutLow', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lowBatteryCutoutMid', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lowBatteryCutoutHigh', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acRecepticles', models.BooleanField(default=True)),
                ('operatingTempMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMin', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            bases=('System_Designer.product',),
        ),
        migrations.CreateModel(
            name='moduleProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System_Designer.Product')),
                ('peakOutputWatts', models.IntegerField()),
                ('operatingVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('peakOutputVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('peakOutputCurrent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('openCircuitVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('shortCircuitCurrent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('maxSystemVoltage', models.DecimalField(decimal_places=1, max_digits=5)),
                ('moduleEffeciency', models.DecimalField(decimal_places=2, max_digits=4)),
                ('connectorType', models.CharField(max_length=200)),
                ('numberOfCells', models.IntegerField()),
                ('operatingTempMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wireSizeOut', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            bases=('System_Designer.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductType', to='System_Designer.Category'),
        ),
        migrations.AddField(
            model_name='load',
            name='accessories',
            field=models.ManyToManyField(through='System_Designer.LoadAccessory', to='System_Designer.Accessory'),
        ),
        migrations.AddField(
            model_name='load',
            name='design_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load', to='System_Designer.DesignProfile'),
        ),
        migrations.AddField(
            model_name='designprofile',
            name='system_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Designer.SystemLevel'),
        ),
        migrations.AddField(
            model_name='designprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_design_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='System_Designer.DesignProfile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-27 05:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('draw_volts', models.IntegerField()),
                ('draw_amps', models.IntegerField()),
                ('draw_watts', models.IntegerField()),
                ('alternating_current', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DesignProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LoadAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_usage', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Designer.Accessory')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Designer.Load')),
            ],
        ),
        migrations.CreateModel(
            name='PowerProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_camping', models.BooleanField()),
                ('vehicular_moves', models.IntegerField()),
                ('days_autonomous', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('length', models.DecimalField(decimal_places=2, max_digits=4)),
                ('width', models.DecimalField(decimal_places=2, max_digits=4)),
                ('height', models.DecimalField(decimal_places=2, max_digits=4)),
                ('warranty', models.TextField(blank=True)),
                ('mfgPartNumber', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserDesignProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Designer.DesignProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleInstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=30)),
                ('panel_type_preference', models.CharField(max_length=1)),
                ('design_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_install', to='System_Designer.DesignProfile')),
            ],
        ),
        migrations.CreateModel(
            name='batteryProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System_Designer.Product')),
                ('ahCapacity', models.PositiveIntegerField()),
                ('operatingVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('chargingCurrentMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('chargingCurrentFloat', models.DecimalField(decimal_places=1, max_digits=4)),
                ('chargingCurrentEqualize', models.DecimalField(decimal_places=1, max_digits=4)),
                ('chargingTempCompensation', models.DecimalField(decimal_places=2, max_digits=4)),
                ('terminalType', models.CharField(max_length=200)),
            ],
            bases=('System_Designer.product',),
        ),
        migrations.CreateModel(
            name='chargeControllerProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System_Designer.Product')),
                ('conversionType', models.CharField(max_length=200)),
                ('maxBattCurrent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('loadCurrentRating', models.DecimalField(decimal_places=1, max_digits=4)),
                ('openCircuitVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('peakEffieciency', models.DecimalField(decimal_places=1, max_digits=4)),
                ('batteryVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('batteryVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('voltageAccuracy', models.DecimalField(decimal_places=1, max_digits=4)),
                ('selfConsumption', models.DecimalField(decimal_places=1, max_digits=4)),
                ('surgeProtection', models.BooleanField(default=True)),
                ('operatingTempMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wireSizeIn', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wireSizeOut', models.DecimalField(decimal_places=1, max_digits=4)),
                ('batteryTemperatureSensor', models.BooleanField(default=True)),
                ('chargeModes', models.CharField(max_length=200)),
            ],
            bases=('System_Designer.product',),
        ),
        migrations.CreateModel(
            name='chargerProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System_Designer.Product')),
                ('dcOuputVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputAmperageContinuous', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dcOutputVoltageFullLoad', models.DecimalField(decimal_places=1, max_digits=4)),
                ('maxPowerOutput', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageFrequency', models.IntegerField()),
                ('maxAcCurrent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('effeciency', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMin', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            bases=('System_Designer.product',),
        ),
        migrations.CreateModel(
            name='inverterChargerProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System_Designer.Product')),
                ('outputWattsContinuous', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputWattsSurge', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputCurrentContinuous', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputFreqency', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputWaveform', models.CharField(max_length=200)),
                ('effeciencyFullLoad', models.DecimalField(decimal_places=1, max_digits=4)),
                ('effeciencyPeak', models.DecimalField(decimal_places=1, max_digits=4)),
                ('noLoadDraw', models.DecimalField(decimal_places=1, max_digits=4)),
                ('offModeDraw', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acInputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acInputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acTransferRelayAmps', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('batteryVoltageNominal', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lowBatteryCutoutLow', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lowBatteryCutoutMid', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lowBatteryCutoutHigh', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acRecepticles', models.BooleanField(default=True)),
                ('operatingTempMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dcOuputVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputAmperageContinuous', models.DecimalField(decimal_places=1, max_digits=4)),
                ('dcOutputVoltageFullLoad', models.DecimalField(decimal_places=1, max_digits=4)),
                ('maxPowerOutput', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageFrequency', models.IntegerField()),
                ('maxAcCurrent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('effeciency', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            bases=('System_Designer.product',),
        ),
        migrations.CreateModel(
            name='inverterProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System_Designer.Product')),
                ('outputWattsContinuous', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputWattsSurge', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputCurrentContinuous', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputFreqency', models.DecimalField(decimal_places=1, max_digits=4)),
                ('outputWaveform', models.CharField(max_length=200)),
                ('effeciencyFullLoad', models.DecimalField(decimal_places=1, max_digits=4)),
                ('effeciencyPeak', models.DecimalField(decimal_places=1, max_digits=4)),
                ('noLoadDraw', models.DecimalField(decimal_places=1, max_digits=4)),
                ('offModeDraw', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acInputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acInputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acTransferRelayAmps', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('inputVoltageMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('batteryVoltageNominal', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lowBatteryCutoutLow', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lowBatteryCutoutMid', models.DecimalField(decimal_places=1, max_digits=4)),
                ('lowBatteryCutoutHigh', models.DecimalField(decimal_places=1, max_digits=4)),
                ('acRecepticles', models.BooleanField(default=True)),
                ('operatingTempMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMin', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            bases=('System_Designer.product',),
        ),
        migrations.CreateModel(
            name='moduleProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='System_Designer.Product')),
                ('peakOutputWatts', models.IntegerField()),
                ('operatingVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('peakOutputVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('peakOutputCurrent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('openCircuitVoltage', models.DecimalField(decimal_places=1, max_digits=4)),
                ('shortCircuitCurrent', models.DecimalField(decimal_places=1, max_digits=4)),
                ('maxSystemVoltage', models.DecimalField(decimal_places=1, max_digits=5)),
                ('moduleEffeciency', models.DecimalField(decimal_places=2, max_digits=4)),
                ('connectorType', models.CharField(max_length=200)),
                ('numberOfCells', models.IntegerField()),
                ('operatingTempMax', models.DecimalField(decimal_places=1, max_digits=4)),
                ('operatingTempMin', models.DecimalField(decimal_places=1, max_digits=4)),
                ('wireSizeOut', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
            bases=('System_Designer.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductType', to='System_Designer.Category'),
        ),
        migrations.AddField(
            model_name='load',
            name='accessories',
            field=models.ManyToManyField(through='System_Designer.LoadAccessory', to='System_Designer.Accessory'),
        ),
        migrations.AddField(
            model_name='load',
            name='design_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load', to='System_Designer.DesignProfile'),
        ),
        migrations.AddField(
            model_name='designprofile',
            name='system_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Designer.SystemLevel'),
        ),
        migrations.AddField(
            model_name='designprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='current_design_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='System_Designer.DesignProfile'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
>>>>>>> Bdev
