# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory', models.CharField(max_length=30)),
                ('wattage', models.IntegerField()),
                ('amperes', models.IntegerField()),
                ('ac_dc', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='DesignProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_autonomous', models.IntegerField()),
                ('winter_camping', models.BooleanField()),
                ('vehicular_moves', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoadAccessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_usage', models.IntegerField()),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Designer.Accessory')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Designer.Load')),
            ],
        ),
        migrations.AddField(
            model_name='load',
            name='accessories',
            field=models.ManyToManyField(through='System_Designer.LoadAccessory', to='System_Designer.Accessory'),
        ),
        migrations.AddField(
            model_name='load',
            name='design_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load', to='System_Designer.DesignProfile'),
        ),
    ]
