# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInstall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=30)),
                ('panel_type_preference', models.CharField(max_length=2)),
                ('design_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_install', to='System_Designer.DesignProfile')),
            ],
        ),
    ]
