# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadaccessory',
            name='drawAmperage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loadaccessory',
            name='drawVoltage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loadaccessory',
            name='drawWatts',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='loadaccessory',
            name='isAc',
            field=models.BooleanField(default=False),
        ),
    ]
