# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-04 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0002_vehicleinstall'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter_camping', models.BooleanField()),
                ('vehicular_moves', models.IntegerField(choices=[(0, 'I just park it!'), (1, 'Once a day, maybe.'), (2, 'I move between a camp location and destination.'), (3, "I'm a taveler, always on the move throughout the day.")])),
            ],
        ),
        migrations.RenameField(
            model_name='accessory',
            old_name='accessory',
            new_name='accessory_name',
        ),
        migrations.RenameField(
            model_name='accessory',
            old_name='amperes',
            new_name='draw_amps',
        ),
        migrations.RenameField(
            model_name='accessory',
            old_name='wattage',
            new_name='draw_volts',
        ),
        migrations.RemoveField(
            model_name='load',
            name='vehicular_moves',
        ),
        migrations.RemoveField(
            model_name='load',
            name='winter_camping',
        ),
        migrations.AddField(
            model_name='accessory',
            name='draw_watts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loadaccessory',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessory',
            name='ac_dc',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='loadaccessory',
            name='estimated_usage',
            field=models.IntegerField(choices=[(0, 'Rarely'), (1, 'A little everyday'), (2, 'A fair amount everyday'), (3, 'With frequency, maybe 3 hours a day.'), (4, 'A lot'), (12, 'all day'), (24, 'Day and night.')]),
        ),
        migrations.AlterField(
            model_name='vehicleinstall',
            name='panel_type_preference',
            field=models.CharField(choices=[('f', 'Fixed panel'), ('m', 'Mounted to the vehicle'), ('b', 'Both fixed panels and additional mounted panels')], max_length=1),
        ),
    ]
