# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-28 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0003_auto_20180527_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadaccessory',
            name='isAc',
            field=models.BooleanField(default=False, verbose_name='AC Load'),
        ),
    ]
