# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-28 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0004_auto_20180527_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessory',
            name='alternating_current',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='draw_amps',
        ),
        migrations.RemoveField(
            model_name='accessory',
            name='draw_volts',
        ),
        migrations.RemoveField(
            model_name='loadaccessory',
            name='drawAmperage',
        ),
        migrations.RemoveField(
            model_name='loadaccessory',
            name='drawVoltage',
        ),
        migrations.RemoveField(
            model_name='loadaccessory',
            name='drawWatts',
        ),
        migrations.RemoveField(
            model_name='loadaccessory',
            name='isAc',
        ),
        migrations.AddField(
            model_name='accessory',
            name='draw_amperage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Amps'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='draw_voltage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Voltage'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='is_Ac',
            field=models.BooleanField(default=False, verbose_name='AC Load'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='user_custom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_accessories', to='System_Designer.Customer'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='draw_watts',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Watts'),
        ),
    ]
