# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('System_Designer', '0005_auto_20180313_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDesignProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='designprofile',
            old_name='profile_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='userdesignprofile',
            name='profile_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Designer.DesignProfile'),
        ),
        migrations.AddField(
            model_name='userdesignprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
