# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-29 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0005_auto_20180528_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_rate', models.IntegerField()),
                ('ah_capacity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_rates', to='System_Designer.batteryProduct')),
            ],
        ),
        migrations.CreateModel(
            name='PanelMounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='powerproduction',
            name='days_autonomous',
        ),
        migrations.AddField(
            model_name='load',
            name='days_autonomous',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='powerproduction',
            name='design_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='power_production', to='System_Designer.DesignProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerproduction',
            name='insolation_multiplyer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powerproduction',
            name='sunlight_hours',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accessory',
            name='draw_amperage',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Amps'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='draw_voltage',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Voltage'),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='draw_watts',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Watts'),
        ),
    ]
