# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-29 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0006_auto_20180529_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
