# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0006_auto_20180322_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='designprofile',
            name='system_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='System_Designer.SystemLevel'),
        ),
    ]
