# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0007_auto_20180322_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='accessory_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='load',
            name='days_autonomous',
        ),
        migrations.AddField(
            model_name='powerproduction',
            name='days_autonomous',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
