# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0008_auto_20180322_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='ac_dc',
            new_name='alternating_current',
        ),
        migrations.AlterField(
            model_name='load',
            name='design_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load', to='System_Designer.UserDesignProfile'),
        ),
    ]
