# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-23 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0009_auto_20180323_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='design_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load', to='System_Designer.DesignProfile'),
        ),
    ]
