# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0009_auto_20180530_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadaccessory',
            name='estimated_usage',
            field=models.FloatField(),
        ),
    ]
