# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-09 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0011_auto_20180603_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='batteryproduct',
            name='optimalDepthOfDischarge',
            field=models.FloatField(default=50),
        ),
    ]
