# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-07 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('System_Designer', '0011_custumer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custumer',
            new_name='Customer',
        ),
    ]
